# Generated by Django 5.2.6 on 2025-09-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=125)),
                ('Last_Name', models.CharField(max_length=125)),
                ('Email', models.CharField(max_length=125)),
                ('Mobile', models.CharField(max_length=12)),
                ('City', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('P', 'Princess'), ('O', 'Other')], max_length=1)),
                ('Goals', models.TextField(max_length=125)),
                ('date', models.DateField()),
            ],
        ),
    ]
