# Generated by Django 5.2.6 on 2025-09-09 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_mobile_contact_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
